# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(536, 699)
        MainWindow.setStyleSheet("background-color:#22222e")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, -20, 540, 270))
        self.frame.setStyleSheet("background-color:#8B008B")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(124, 50, 291, 42))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(-40, 110, 411, 281))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Downloads/images-fotor-bg-remover-20231030171918.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(185, 90, 170, 121))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("foto/dickt_2.png"))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(345, 210, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color:#6A5ACD;\n"
"border: 2px solid #f66867;\n"
"color: white;\n"
"border-radius: 20\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 210, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color:#6A5ACD;\n"
"border: 2px solid #f66867;\n"
"color: white;\n"
"border-radius: 20\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(460, 30, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{background-color:#6A5ACD;border: 2px solid #f66867;}\n"
"QPushButton:pressed{\n"
"background-color: #fa4244\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.line_1_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_1_1.setGeometry(QtCore.QRect(30, 300, 176, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.line_1_1.setFont(font)
        self.line_1_1.setStyleSheet("background-color:#6A5ACD;\n"
"border: 2px solid #f66867;\n"
"color: white;\n"
"border-radius: 20\n"
"\n"
"")
        self.line_1_1.setText("")
        self.line_1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.line_1_1.setObjectName("line_1_1")
        self.line_1_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_1_2.setGeometry(QtCore.QRect(330, 290, 176, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.line_1_2.setFont(font)
        self.line_1_2.setStyleSheet("background-color:#6A5ACD;\n"
"border: 2px solid #f66867;\n"
"color: white;\n"
"border-radius: 20\n"
"\n"
"")
        self.line_1_2.setText("")
        self.line_1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.line_1_2.setObjectName("line_1_2")
        self.line_2_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_2_2.setGeometry(QtCore.QRect(330, 364, 176, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.line_2_2.setFont(font)
        self.line_2_2.setStyleSheet("background-color:#6A5ACD;\n"
"border: 2px solid #f66867;\n"
"color: white;\n"
"border-radius: 20\n"
"\n"
"")
        self.line_2_2.setText("")
        self.line_2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.line_2_2.setObjectName("line_2_2")
        self.line_2_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_2_1.setGeometry(QtCore.QRect(30, 370, 176, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.line_2_1.setFont(font)
        self.line_2_1.setStyleSheet("background-color:#6A5ACD;\n"
"border: 2px solid #f66867;\n"
"color: white;\n"
"border-radius: 20\n"
"\n"
"")
        self.line_2_1.setText("")
        self.line_2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.line_2_1.setObjectName("line_2_1")
        self.line_3_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_3_1.setGeometry(QtCore.QRect(30, 440, 176, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.line_3_1.setFont(font)
        self.line_3_1.setStyleSheet("background-color:#6A5ACD;\n"
"border: 2px solid #f66867;\n"
"color: white;\n"
"border-radius: 20\n"
"\n"
"")
        self.line_3_1.setText("")
        self.line_3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.line_3_1.setObjectName("line_3_1")
        self.line_3_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_3_2.setGeometry(QtCore.QRect(330, 438, 176, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.line_3_2.setFont(font)
        self.line_3_2.setStyleSheet("background-color:#6A5ACD;\n"
"border: 2px solid #f66867;\n"
"color: white;\n"
"border-radius: 20\n"
"\n"
"")
        self.line_3_2.setText("")
        self.line_3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.line_3_2.setObjectName("line_3_2")
        self.line_4_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_4_1.setGeometry(QtCore.QRect(30, 510, 176, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.line_4_1.setFont(font)
        self.line_4_1.setStyleSheet("background-color:#6A5ACD;\n"
"border: 2px solid #f66867;\n"
"color: white;\n"
"border-radius: 20\n"
"")
        self.line_4_1.setText("")
        self.line_4_1.setAlignment(QtCore.Qt.AlignCenter)
        self.line_4_1.setObjectName("line_4_1")
        self.line_4_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_4_2.setGeometry(QtCore.QRect(330, 512, 176, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.line_4_2.setFont(font)
        self.line_4_2.setStyleSheet("background-color:#6A5ACD;\n"
"border: 2px solid #f66867;\n"
"color: white;\n"
"border-radius: 20\n"
"\n"
"")
        self.line_4_2.setText("")
        self.line_4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.line_4_2.setObjectName("line_4_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(122, 600, 292, 42))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"background-color:#fb5b5d;\n"
"border-radius:21\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: #fa4244\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.check_2 = QtWidgets.QLabel(self.centralwidget)
        self.check_2.setGeometry(QtCore.QRect(240, 360, 61, 61))
        self.check_2.setText("")
        self.check_2.setObjectName("check_2")
        self.check_3 = QtWidgets.QLabel(self.centralwidget)
        self.check_3.setGeometry(QtCore.QRect(240, 430, 61, 61))
        self.check_3.setText("")
        self.check_3.setObjectName("check_3")
        self.check_4 = QtWidgets.QLabel(self.centralwidget)
        self.check_4.setGeometry(QtCore.QRect(240, 500, 61, 61))
        self.check_4.setText("")
        self.check_4.setObjectName("check_4")
        self.check_1 = QtWidgets.QLabel(self.centralwidget)
        self.check_1.setGeometry(QtCore.QRect(240, 290, 61, 61))
        self.check_1.setText("")
        self.check_1.setObjectName("check_1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 536, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Английский словарик"))
        self.pushButton_2.setText(_translate("MainWindow", "Проверка себя"))
        self.pushButton_3.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_4.setText(_translate("MainWindow", "?"))
        self.pushButton.setText(_translate("MainWindow", "Проверка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
